city = [('', 'Kota'), ('Aceh Barat', 'Aceh Barat'), ('Aceh Barat Daya', 'Aceh Barat Daya'),
        ('Aceh Besar', 'Aceh Besar'),
        ('Aceh Jaya', 'Aceh Jaya'), ('Aceh Selatan', 'Aceh Selatan'), ('Aceh Singkil', 'Aceh Singkil'),
        ('Aceh Tamiang', 'Aceh Tamiang'), ('Aceh Tengah', 'Aceh Tengah'), ('Aceh Tenggara', 'Aceh Tenggara'),
        ('Aceh Timur', 'Aceh Timur'), ('Aceh Utara', 'Aceh Utara'), ('Agam', 'Agam'), ('Alor', 'Alor'),
        ('Ambon', 'Ambon'),
        ('Asahan', 'Asahan'), ('Asmat', 'Asmat'), ('Batam', 'Batam'), ('Badung', 'Badung'), ('Balangan', 'Balangan'),
        ('Balikpapan', 'Balikpapan'), ('Banda Aceh', 'Banda Aceh'), ('Bandar Lampung', 'Bandar Lampung'),
        ('Bandung', 'Bandung'), ('Bandung Barat', 'Bandung Barat'), ('Banggai', 'Banggai'),
        ('Banggai Kepulauan', 'Banggai Kepulauan'), ('Bangka', 'Bangka'), ('Bangka Barat', 'Bangka Barat'),
        ('Bangka Selatan', 'Bangka Selatan'), ('Bangka Tengah', 'Bangka Tengah'), ('Bangkalan', 'Bangkalan'),
        ('Bangli', 'Bangli'), ('Banjar', 'Banjar'), ('Banjar Baru', 'Banjar Baru'), ('Banjarmasin', 'Banjarmasin'),
        ('Banjarnegara', 'Banjarnegara'), ('Bantaeng', 'Bantaeng'), ('Bantul', 'Bantul'), ('Banyu Asin', 'Banyu Asin'),
        ('Banyumas', 'Banyumas'), ('Banyuwangi', 'Banyuwangi'), ('Barito Kuala', 'Barito Kuala'),
        ('Barito Selatan', 'Barito Selatan'), ('Barito Timur', 'Barito Timur'), ('Barito Utara', 'Barito Utara'),
        ('Barru', 'Barru'), ('Baru', 'Baru'), ('Batang', 'Batang'), ('Batang Hari', 'Batang Hari'), ('Batu', 'Batu'),
        ('Batu Bara', 'Batu Bara'), ('Baubau', 'Baubau'), ('Bekasi', 'Bekasi'), ('Belitung', 'Belitung'),
        ('Belitung Timur', 'Belitung Timur'), ('Belu', 'Belu'), ('Bener Meriah', 'Bener Meriah'),
        ('Bengkalis', 'Bengkalis'), ('Bengkayang', 'Bengkayang'), ('Bengkulu', 'Bengkulu'),
        ('Bengkulu Selatan', 'Bengkulu Selatan'), ('Bengkulu Tengah', 'Bengkulu Tengah'),
        ('Bengkulu Utara', 'Bengkulu Utara'), ('Berau', 'Berau'), ('Biak Numfor', 'Biak Numfor'), ('Bima', 'Bima'),
        ('Binjai', 'Binjai'), ('Bintan', 'Bintan'), ('Bireuen', 'Bireuen'), ('Bitung', 'Bitung'), ('Blitar', 'Blitar'),
        ('Blora', 'Blora'), ('Boalemo', 'Boalemo'), ('Bogor', 'Bogor'), ('Bojonegoro', 'Bojonegoro'),
        ('Bolaang Mongondow', 'Bolaang Mongondow'), ('Bolaang Mongondow Selatan', 'Bolaang Mongondow Selatan'),
        ('Bolaang Mongondow Timur', 'Bolaang Mongondow Timur'), ('Bolaang Mongondow Utara', 'Bolaang Mongondow Utara'),
        ('Bombana', 'Bombana'), ('Bondowoso', 'Bondowoso'), ('Bone', 'Bone'), ('Bone Bolango', 'Bone Bolango'),
        ('Bontang', 'Bontang'), ('Boven Digoel', 'Boven Digoel'), ('Boyolali', 'Boyolali'), ('Brebes', 'Brebes'),
        ('Bukittinggi', 'Bukittinggi'), ('Buleleng', 'Buleleng'), ('Bulukumba', 'Bulukumba'), ('Bulungan', 'Bulungan'),
        ('Bungo', 'Bungo'), ('Buol', 'Buol'), ('Buru', 'Buru'), ('Buru Selatan', 'Buru Selatan'), ('Buton', 'Buton'),
        ('Buton Utara', 'Buton Utara'), ('Ciamis', 'Ciamis'), ('Cianjur', 'Cianjur'), ('Cilacap', 'Cilacap'),
        ('Cilegon', 'Cilegon'), ('Cimahi', 'Cimahi'), ('Cirebon', 'Cirebon'), ('Dumai', 'Dumai'), ('Dairi', 'Dairi'),
        ('Deiyai', 'Deiyai'), ('Deli Serdang', 'Deli Serdang'), ('Demak', 'Demak'), ('Denpasar', 'Denpasar'),
        ('Depok', 'Depok'), ('Dharmasraya', 'Dharmasraya'), ('Dogiyai', 'Dogiyai'), ('Dompu', 'Dompu'),
        ('Donggala', 'Donggala'), ('Empat Lawang', 'Empat Lawang'), ('Ende', 'Ende'), ('Enrekang', 'Enrekang'),
        ('Fakfak', 'Fakfak'), ('Flores Timur', 'Flores Timur'), ('Garut', 'Garut'), ('Gayo Lues', 'Gayo Lues'),
        ('Gianyar', 'Gianyar'), ('Gorontalo', 'Gorontalo'), ('Gorontalo Utara', 'Gorontalo Utara'), ('Gowa', 'Gowa'),
        ('Gresik', 'Gresik'), ('Grobogan', 'Grobogan'), ('Gunung Kidul', 'Gunung Kidul'), ('Gunung Mas', 'Gunung Mas'),
        ('Gunungsitoli', 'Gunungsitoli'), ('Halmahera Barat', 'Halmahera Barat'),
        ('Halmahera Selatan', 'Halmahera Selatan'), ('Halmahera Tengah', 'Halmahera Tengah'),
        ('Halmahera Timur', 'Halmahera Timur'), ('Halmahera Utara', 'Halmahera Utara'),
        ('Hulu Sungai Selatan', 'Hulu Sungai Selatan'), ('Hulu Sungai Tengah', 'Hulu Sungai Tengah'),
        ('Hulu Sungai Utara', 'Hulu Sungai Utara'), ('Humbang Hasundutan', 'Humbang Hasundutan'),
        ('Indragiri Hilir', 'Indragiri Hilir'), ('Indragiri Hulu', 'Indragiri Hulu'), ('Indramayu', 'Indramayu'),
        ('Intan Jaya', 'Intan Jaya'), ('Jakarta Barat', 'Jakarta Barat'), ('Jakarta Pusat', 'Jakarta Pusat'),
        ('Jakarta Selatan', 'Jakarta Selatan'), ('Jakarta Timur', 'Jakarta Timur'), ('Jakarta Utara', 'Jakarta Utara'),
        ('Jambi', 'Jambi'), ('Jayapura', 'Jayapura'), ('Jayawijaya', 'Jayawijaya'), ('Jember', 'Jember'),
        ('Jembrana', 'Jembrana'), ('Jeneponto', 'Jeneponto'), ('Jepara', 'Jepara'), ('Jombang', 'Jombang'),
        ('Kaimana', 'Kaimana'), ('Kampar', 'Kampar'), ('Kapuas', 'Kapuas'), ('Kapuas Hulu', 'Kapuas Hulu'),
        ('Karang Asem', 'Karang Asem'), ('Karanganyar', 'Karanganyar'), ('Karawang', 'Karawang'),
        ('Karimun', 'Karimun'),
        ('Karo', 'Karo'), ('Katingan', 'Katingan'), ('Kaur', 'Kaur'), ('Kayong Utara', 'Kayong Utara'),
        ('Kebumen', 'Kebumen'), ('Kediri', 'Kediri'), ('Keerom', 'Keerom'), ('Kendal', 'Kendal'),
        ('Kendari', 'Kendari'),
        ('Kepahiang', 'Kepahiang'), ('Kepulauan Anambas', 'Kepulauan Anambas'), ('Kepulauan Aru', 'Kepulauan Aru'),
        ('Kepulauan Mentawai', 'Kepulauan Mentawai'), ('Kepulauan Meranti', 'Kepulauan Meranti'),
        ('Kepulauan Sangihe', 'Kepulauan Sangihe'), ('Kepulauan Selayar', 'Kepulauan Selayar'),
        ('Kepulauan Seribu', 'Kepulauan Seribu'), ('Kepulauan Sula', 'Kepulauan Sula'),
        ('Kepulauan Talaud', 'Kepulauan Talaud'), ('Kepulauan Yapen', 'Kepulauan Yapen'), ('Kerinci', 'Kerinci'),
        ('Ketapang', 'Ketapang'), ('Klaten', 'Klaten'), ('Klungkung', 'Klungkung'), ('Kolaka', 'Kolaka'),
        ('Kolaka Utara', 'Kolaka Utara'), ('Konawe', 'Konawe'), ('Konawe Selatan', 'Konawe Selatan'),
        ('Konawe Utara', 'Konawe Utara'), ('Kotamobagu', 'Kotamobagu'), ('Kotawaringin Barat', 'Kotawaringin Barat'),
        ('Kotawaringin Timur', 'Kotawaringin Timur'), ('Kuantan Singingi', 'Kuantan Singingi'),
        ('Kubu Raya', 'Kubu Raya'),
        ('Kudus', 'Kudus'), ('Kulon Progo', 'Kulon Progo'), ('Kuningan', 'Kuningan'), ('Kupang', 'Kupang'),
        ('Kutai Barat', 'Kutai Barat'), ('Kutai Kartanegara', 'Kutai Kartanegara'), ('Kutai Timur', 'Kutai Timur'),
        ('Labuhan Batu', 'Labuhan Batu'), ('Labuhan Batu Selatan', 'Labuhan Batu Selatan'),
        ('Labuhan Batu Utara', 'Labuhan Batu Utara'), ('Lahat', 'Lahat'), ('Lamandau', 'Lamandau'),
        ('Lamongan', 'Lamongan'), ('Lampung Barat', 'Lampung Barat'), ('Lampung Selatan', 'Lampung Selatan'),
        ('Lampung Tengah', 'Lampung Tengah'), ('Lampung Timur', 'Lampung Timur'), ('Lampung Utara', 'Lampung Utara'),
        ('Landak', 'Landak'), ('Langkat', 'Langkat'), ('Langsa', 'Langsa'), ('Lanny Jaya', 'Lanny Jaya'),
        ('Lebak', 'Lebak'), ('Lebong', 'Lebong'), ('Lembata', 'Lembata'), ('Lhokseumawe', 'Lhokseumawe'),
        ('Lima Puluh Kota', 'Lima Puluh Kota'), ('Lingga', 'Lingga'), ('Lombok Barat', 'Lombok Barat'),
        ('Lombok Tengah', 'Lombok Tengah'), ('Lombok Timur', 'Lombok Timur'), ('Lombok Utara', 'Lombok Utara'),
        ('Lubuklinggau', 'Lubuklinggau'), ('Lumajang', 'Lumajang'), ('Luwu', 'Luwu'), ('Luwu Timur', 'Luwu Timur'),
        ('Luwu Utara', 'Luwu Utara'), ('Madiun', 'Madiun'), ('Magelang', 'Magelang'), ('Magetan', 'Magetan'),
        ('Majalengka', 'Majalengka'), ('Majene', 'Majene'), ('Makassar', 'Makassar'), ('Malang', 'Malang'),
        ('Malinau', 'Malinau'), ('Maluku Barat Daya', 'Maluku Barat Daya'), ('Maluku Tengah', 'Maluku Tengah'),
        ('Maluku Tenggara', 'Maluku Tenggara'), ('Maluku Tenggara Barat', 'Maluku Tenggara Barat'),
        ('Mamasa', 'Mamasa'),
        ('Mamberamo Raya', 'Mamberamo Raya'), ('Mamberamo Tengah', 'Mamberamo Tengah'), ('Mamuju', 'Mamuju'),
        ('Mamuju Utara', 'Mamuju Utara'), ('Manado', 'Manado'), ('Mandailing Natal', 'Mandailing Natal'),
        ('Manggarai', 'Manggarai'), ('Manggarai Barat', 'Manggarai Barat'), ('Manggarai Timur', 'Manggarai Timur'),
        ('Manokwari', 'Manokwari'), ('Mappi', 'Mappi'), ('Maros', 'Maros'), ('Mataram', 'Mataram'),
        ('Maybrat', 'Maybrat'),
        ('Medan', 'Medan'), ('Melawi', 'Melawi'), ('Merangin', 'Merangin'), ('Merauke', 'Merauke'),
        ('Mesuji', 'Mesuji'),
        ('Metro', 'Metro'), ('Mimika', 'Mimika'), ('Minahasa', 'Minahasa'), ('Minahasa Selatan', 'Minahasa Selatan'),
        ('Minahasa Tenggara', 'Minahasa Tenggara'), ('Minahasa Utara', 'Minahasa Utara'), ('Mojokerto', 'Mojokerto'),
        ('Morowali', 'Morowali'), ('Muara Enim', 'Muara Enim'), ('Muaro Jambi', 'Muaro Jambi'),
        ('Mukomuko', 'Mukomuko'),
        ('Muna', 'Muna'), ('Murung Raya', 'Murung Raya'), ('Musi Banyuasin', 'Musi Banyuasin'),
        ('Musi Rawas', 'Musi Rawas'), ('Nabire', 'Nabire'), ('Nagan Raya', 'Nagan Raya'), ('Nagekeo', 'Nagekeo'),
        ('Natuna', 'Natuna'), ('Nduga', 'Nduga'), ('Ngada', 'Ngada'), ('Nganjuk', 'Nganjuk'), ('Ngawi', 'Ngawi'),
        ('Nias', 'Nias'), ('Nias Barat', 'Nias Barat'), ('Nias Selatan', 'Nias Selatan'), ('Nias Utara', 'Nias Utara'),
        ('Nunukan', 'Nunukan'), ('Ogan Ilir', 'Ogan Ilir'), ('Ogan Komering Ilir', 'Ogan Komering Ilir'),
        ('Ogan Komering Ulu', 'Ogan Komering Ulu'), ('Ogan Komering Ulu Selatan', 'Ogan Komering Ulu Selatan'),
        ('Ogan Komering Ulu Timur', 'Ogan Komering Ulu Timur'), ('Pacitan', 'Pacitan'), ('Padang', 'Padang'),
        ('Padang Lawas', 'Padang Lawas'), ('Padang Lawas Utara', 'Padang Lawas Utara'),
        ('Padang Panjang', 'Padang Panjang'), ('Padang Pariaman', 'Padang Pariaman'),
        ('Padangsidimpuan', 'Padangsidimpuan'), ('Pagar Alam', 'Pagar Alam'), ('Pakpak Bharat', 'Pakpak Bharat'),
        ('Palangka Raya', 'Palangka Raya'), ('Palembang', 'Palembang'), ('Palopo', 'Palopo'), ('Palu', 'Palu'),
        ('Pamekasan', 'Pamekasan'), ('Pandeglang', 'Pandeglang'), ('Pangandaran', 'Pangandaran'),
        ('Pangkajene Dan Kepulauan', 'Pangkajene Dan Kepulauan'), ('Pangkal Pinang', 'Pangkal Pinang'),
        ('Paniai', 'Paniai'), ('Parepare', 'Parepare'), ('Pariaman', 'Pariaman'), ('Parigi Moutong', 'Parigi Moutong'),
        ('Pasaman', 'Pasaman'), ('Pasaman Barat', 'Pasaman Barat'), ('Paser', 'Paser'), ('Pasuruan', 'Pasuruan'),
        ('Pati', 'Pati'), ('Payakumbuh', 'Payakumbuh'), ('Pegunungan Bintang', 'Pegunungan Bintang'),
        ('Pekalongan', 'Pekalongan'), ('Pekanbaru', 'Pekanbaru'), ('Pelalawan', 'Pelalawan'), ('Pemalang', 'Pemalang'),
        ('Pematang Siantar', 'Pematang Siantar'), ('Penajam Paser Utara', 'Penajam Paser Utara'),
        ('Pesawaran', 'Pesawaran'), ('Pesisir Barat', 'Pesisir Barat'), ('Pesisir Selatan', 'Pesisir Selatan'),
        ('Pidie', 'Pidie'), ('Pidie Jaya', 'Pidie Jaya'), ('Pinrang', 'Pinrang'), ('Pohuwato', 'Pohuwato'),
        ('Polewali Mandar', 'Polewali Mandar'), ('Ponorogo', 'Ponorogo'), ('Pontianak', 'Pontianak'), ('Poso', 'Poso'),
        ('Prabumulih', 'Prabumulih'), ('Pringsewu', 'Pringsewu'), ('Probolinggo', 'Probolinggo'),
        ('Pulang Pisau', 'Pulang Pisau'), ('Pulau Morotai', 'Pulau Morotai'), ('Puncak', 'Puncak'),
        ('Puncak Jaya', 'Puncak Jaya'), ('Purbalingga', 'Purbalingga'), ('Purwakarta', 'Purwakarta'),
        ('Purworejo', 'Purworejo'), ('Raja Ampat', 'Raja Ampat'), ('Rejang Lebong', 'Rejang Lebong'),
        ('Rembang', 'Rembang'), ('Rokan Hilir', 'Rokan Hilir'), ('Rokan Hulu', 'Rokan Hulu'),
        ('Rote Ndao', 'Rote Ndao'),
        ('Siak', 'Siak'), ('Sabang', 'Sabang'), ('Sabu Raijua', 'Sabu Raijua'), ('Salatiga', 'Salatiga'),
        ('Samarinda', 'Samarinda'), ('Sambas', 'Sambas'), ('Samosir', 'Samosir'), ('Sampang', 'Sampang'),
        ('Sanggau', 'Sanggau'), ('Sarmi', 'Sarmi'), ('Sarolangun', 'Sarolangun'), ('Sawah Lunto', 'Sawah Lunto'),
        ('Sekadau', 'Sekadau'), ('Seluma', 'Seluma'), ('Semarang', 'Semarang'),
        ('Seram Bagian Barat', 'Seram Bagian Barat'), ('Seram Bagian Timur', 'Seram Bagian Timur'),
        ('Serang', 'Serang'),
        ('Serdang Bedagai', 'Serdang Bedagai'), ('Seruyan', 'Seruyan'),
        ('Siau Tagulandang Biaro', 'Siau Tagulandang Biaro'), ('Sibolga', 'Sibolga'),
        ('Sidenreng Rappang', 'Sidenreng Rappang'), ('Sidoarjo', 'Sidoarjo'), ('Sigi', 'Sigi'),
        ('Sijunjung', 'Sijunjung'),
        ('Sikka', 'Sikka'), ('Simalungun', 'Simalungun'), ('Simeulue', 'Simeulue'), ('Singkawang', 'Singkawang'),
        ('Sinjai', 'Sinjai'), ('Sintang', 'Sintang'), ('Situbondo', 'Situbondo'), ('Sleman', 'Sleman'),
        ('Solok', 'Solok'),
        ('Solok Selatan', 'Solok Selatan'), ('Soppeng', 'Soppeng'), ('Sorong', 'Sorong'),
        ('Sorong Selatan', 'Sorong Selatan'), ('Sragen', 'Sragen'), ('Subang', 'Subang'),
        ('Subulussalam', 'Subulussalam'),
        ('Sukabumi', 'Sukabumi'), ('Sukamara', 'Sukamara'), ('Sukoharjo', 'Sukoharjo'), ('Sumba Barat', 'Sumba Barat'),
        ('Sumba Barat Daya', 'Sumba Barat Daya'), ('Sumba Tengah', 'Sumba Tengah'), ('Sumba Timur', 'Sumba Timur'),
        ('Sumbawa', 'Sumbawa'), ('Sumbawa Barat', 'Sumbawa Barat'), ('Sumedang', 'Sumedang'), ('Sumenep', 'Sumenep'),
        ('Sungai Penuh', 'Sungai Penuh'), ('Supiori', 'Supiori'), ('Surabaya', 'Surabaya'), ('Surakarta', 'Surakarta'),
        ('Tabalong', 'Tabalong'), ('Tabanan', 'Tabanan'), ('Takalar', 'Takalar'), ('Tambrauw', 'Tambrauw'),
        ('Tana Tidung', 'Tana Tidung'), ('Tana Toraja', 'Tana Toraja'), ('Tanah Bumbu', 'Tanah Bumbu'),
        ('Tanah Datar', 'Tanah Datar'), ('Tanah Laut', 'Tanah Laut'), ('Tangerang', 'Tangerang'),
        ('Tangerang Selatan', 'Tangerang Selatan'), ('Tanggamus', 'Tanggamus'), ('Tanjung Balai', 'Tanjung Balai'),
        ('Tanjung Jabung Barat', 'Tanjung Jabung Barat'), ('Tanjung Jabung Timur', 'Tanjung Jabung Timur'),
        ('Tanjung Pinang', 'Tanjung Pinang'), ('Tapanuli Selatan', 'Tapanuli Selatan'),
        ('Tapanuli Tengah', 'Tapanuli Tengah'), ('Tapanuli Utara', 'Tapanuli Utara'), ('Tapin', 'Tapin'),
        ('Tarakan', 'Tarakan'), ('Tasikmalaya', 'Tasikmalaya'), ('Tebing Tinggi', 'Tebing Tinggi'), ('Tebo', 'Tebo'),
        ('Tegal', 'Tegal'), ('Teluk Bintuni', 'Teluk Bintuni'), ('Teluk Wondama', 'Teluk Wondama'),
        ('Temanggung', 'Temanggung'), ('Ternate', 'Ternate'), ('Tidore Kepulauan', 'Tidore Kepulauan'),
        ('Timor Tengah Selatan', 'Timor Tengah Selatan'), ('Timor Tengah Utara', 'Timor Tengah Utara'),
        ('Toba Samosir', 'Toba Samosir'), ('Tojo Una-una', 'Tojo Una-una'), ('Toli-toli', 'Toli-toli'),
        ('Tolikara', 'Tolikara'), ('Tomohon', 'Tomohon'), ('Toraja Utara', 'Toraja Utara'),
        ('Trenggalek', 'Trenggalek'),
        ('Tual', 'Tual'), ('Tuban', 'Tuban'), ('Tulang Bawang Barat', 'Tulang Bawang Barat'),
        ('Tulangbawang', 'Tulangbawang'), ('Tulungagung', 'Tulungagung'), ('Wajo', 'Wajo'), ('Wakatobi', 'Wakatobi'),
        ('Waropen', 'Waropen'), ('Way Kanan', 'Way Kanan'), ('Wonogiri', 'Wonogiri'), ('Wonosobo', 'Wonosobo'),
        ('Yahukimo', 'Yahukimo'), ('Yalimo', 'Yalimo'), ('Yogyakarta', 'Yogyakarta')]
